import { MascotType, MascotCategory } from '../types';

export interface MascotInfo {
  id: MascotType;
  name: string;
  title: string;
  tagline: string;
  emoji: string;
  accent: string;
  bgBadge: string;
  category: MascotCategory;
  formType: 'human' | 'animal' | 'mythical' | 'cyber';
  gender: 'female' | 'male' | 'neutral';
  archetype: string;
}

export const MASCOT_CATEGORIES: { id: MascotCategory; label: string; icon: string; desc: string }[] = [
  { id: 'ALL', label: 'Tất cả', icon: '✨', desc: 'Toàn bộ dàn nhân vật & linh vật' },
  { id: 'HUMAN', label: 'Dạng Người / Anime', icon: '🧑', desc: 'Học sinh, Sensei, Idol, Maid, DJ, Yandere, Ninja, Pháp sư' },
  { id: 'ANIMAL', label: 'Linh Vật Độc Bản', icon: '🐾', desc: 'Mỗi loài đúng 1 linh vật độc nhất: Cú, Mèo, Cáo, Shiba, Gấu, Thỏ...' },
  { id: 'POWER', label: 'Uy Quyền & Lãnh Đạo', icon: '👑', desc: 'Chủ tịch, Thủ lĩnh, Nữ hoàng, Sensei, CEO' },
  { id: 'COOL', label: 'Cao Lãnh & Cá Tính', icon: '❄️', desc: 'Long đế, Kuudere, Tsundere, Quý tộc, Quạ hắc ám, Ninja' },
  { id: 'FRIEND', label: 'Gần Gũi & Tình Cảm', icon: '🌸', desc: 'Thanh mai trúc mã, Bạn thân, Chị gái, Em gái, Bạn cùng lớp' },
  { id: 'FUN', label: 'Hài Hước & Gen Z', icon: '⚡', desc: 'Shiba, Khỉ siêu quậy, Meme Pepe, Gamer, Wibu' },
  { id: 'FANTASY', label: 'Huyền Ảo & Phép Thuật', icon: '🔮', desc: 'Pháp sư, Công chúa, Kỵ sĩ, Ma vương, Vampire, Slime, Ghost' },
  { id: 'SPECIAL', label: 'Đặc Biệt & Độc Đáo', icon: '🎭', desc: 'Idol, Maid, Thám tử, Hacker, DJ, Streamer, Yandere' },
];

export const MASCOT_LIST: MascotInfo[] = [
  // ================= DẠNG NGƯỜI / ANIME =================
  {
    id: 'osananajimi',
    name: 'Cô Bạn Thanh Mai',
    title: 'Thanh Mai Trúc Mã',
    tagline: 'Gắn bó từ nhỏ, tóc bím thắt nơ, hay cằn nhằn nhưng quan tâm nhất',
    emoji: '👧',
    accent: '#f59e0b',
    bgBadge: 'bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/30',
    category: 'FRIEND',
    formType: 'human',
    gender: 'female',
    archetype: 'Thanh mai trúc mã'
  },
  {
    id: 'student_boy',
    name: 'Nam Sinh Bàn Bên',
    title: 'Cậu Bạn Năng Động',
    tagline: 'Áo hoodie thể thao, luôn chia sẻ bài tập và gánh bạn qua kỳ thi',
    emoji: '👦',
    accent: '#3b82f6',
    bgBadge: 'bg-blue-500/15 text-blue-600 dark:text-blue-400 border-blue-500/30',
    category: 'FRIEND',
    formType: 'human',
    gender: 'male',
    archetype: 'Bạn cùng lớp nam'
  },
  {
    id: 'tsundere',
    name: 'Tiểu Thư Tsundere',
    title: 'Nữ Sinh Đanh Đá',
    tagline: 'Tóc vàng twintail hai bên. Hừ! Không phải tớ cố ý nhắc bài đâu nhé... Baka!',
    emoji: '👱‍♀️',
    accent: '#f97316',
    bgBadge: 'bg-orange-500/15 text-orange-600 dark:text-orange-400 border-orange-500/30',
    category: 'COOL',
    formType: 'human',
    gender: 'female',
    archetype: 'Tsundere'
  },
  {
    id: 'kuudere',
    name: 'Băng Nhi Kuudere',
    title: 'Nữ Sinh Băng Lãnh',
    tagline: 'Tóc bạch kim, khăn len xanh, kiệm lời nhưng luôn chữa đúng trọng tâm',
    emoji: '❄️',
    accent: '#38bdf8',
    bgBadge: 'bg-sky-500/15 text-sky-600 dark:text-sky-400 border-sky-500/30',
    category: 'COOL',
    formType: 'human',
    gender: 'female',
    archetype: 'Kuudere'
  },
  {
    id: 'headmaster',
    name: 'Thầy Giáo Soái Ca',
    title: 'Sensei Nghiêm Khắc',
    tagline: 'Kính mắt tri thức, sơ mi cà vạt lịch lãm, kỷ luật chuẩn mực sư phạm',
    emoji: '👨‍🏫',
    accent: '#059669',
    bgBadge: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/30',
    category: 'POWER',
    formType: 'human',
    gender: 'male',
    archetype: 'Hiệu trưởng / Sensei'
  },
  {
    id: 'young_ceo',
    name: 'Tổng Tài Trẻ',
    title: 'CEO Quyết Đoán',
    tagline: 'Vest xanh navy sang trọng. Thời gian là tiền bạc, hiệu suất tối đa',
    emoji: '👔',
    accent: '#0284c7',
    bgBadge: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400 border-cyan-500/30',
    category: 'POWER',
    formType: 'human',
    gender: 'male',
    archetype: 'CEO trẻ'
  },
  {
    id: 'oneesan',
    name: 'Chị Gái Onee-san',
    title: 'Đàn Chị Dịu Dàng',
    tagline: 'Ara ara~ Để chị kèm em học từng bước, đừng ngại nhé cưng',
    emoji: '👩‍💼',
    accent: '#ec4899',
    bgBadge: 'bg-pink-500/15 text-pink-600 dark:text-pink-400 border-pink-500/30',
    category: 'FRIEND',
    formType: 'human',
    gender: 'female',
    archetype: 'Chị gái'
  },
  {
    id: 'imouto',
    name: 'Bé Em Gái',
    title: 'Em Gái Nhí Nhảnh',
    tagline: 'Tóc búi củ tỏi kẹp nơ dâu tây: Onii-chan/Onee-chan giải bài giúp em đi mà~',
    emoji: '👧',
    accent: '#f43f5e',
    bgBadge: 'bg-rose-500/15 text-rose-600 dark:text-rose-400 border-rose-500/30',
    category: 'FRIEND',
    formType: 'human',
    gender: 'female',
    archetype: 'Em gái'
  },
  {
    id: 'idol',
    name: 'Thần Tượng Idol',
    title: 'Idol Quốc Dân',
    tagline: 'Tóc hồng bồng bềnh, mic biểu diễn: Kira kira~! Bắn tim tiếp năng lượng 1000%',
    emoji: '🎤',
    accent: '#ec4899',
    bgBadge: 'bg-pink-500/15 text-pink-600 dark:text-pink-400 border-pink-500/30',
    category: 'SPECIAL',
    formType: 'human',
    gender: 'female',
    archetype: 'Idol'
  },
  {
    id: 'maid',
    name: 'Hầu Gái Quý Tộc',
    title: 'Maid Tận Tâm',
    tagline: 'Băng đô ren trắng, nơ cổ đen: Goshujin-sama, em xin phục vụ việc học của ngài ạ',
    emoji: '🎀',
    accent: '#3b82f6',
    bgBadge: 'bg-blue-500/15 text-blue-600 dark:text-blue-400 border-blue-500/30',
    category: 'SPECIAL',
    formType: 'human',
    gender: 'female',
    archetype: 'Maid'
  },
  {
    id: 'detective',
    name: 'Thám Tử Lừng Danh',
    title: 'Thám Tử Suy Luận',
    tagline: 'Mũ fedora Sherlock, áo măng tô: Chân tướng câu trả lời chỉ có một!',
    emoji: '🔍',
    accent: '#78350f',
    bgBadge: 'bg-amber-700/15 text-amber-700 dark:text-amber-400 border-amber-700/30',
    category: 'SPECIAL',
    formType: 'human',
    gender: 'male',
    archetype: 'Thám tử'
  },
  {
    id: 'dj_girl',
    name: 'DJ Cyberpunk',
    title: 'DJ Âm Nhạc Neon',
    tagline: 'Tai nghe DJ phát sáng, tóc nhuộm neon: Drop beat cực căng, quẩy nát ngữ pháp!',
    emoji: '🎧',
    accent: '#06b6d4',
    bgBadge: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400 border-cyan-500/30',
    category: 'SPECIAL',
    formType: 'human',
    gender: 'female',
    archetype: 'DJ / Audio girl'
  },
  {
    id: 'streamer',
    name: 'VTuber Triệu Sub',
    title: 'Streamer Nhí Nhảnh',
    tagline: 'Tai nghe tai mèo RGB, tóc tím lilac: Chào cả nhà iu, donate điểm 10 nha!',
    emoji: '📺',
    accent: '#a855f7',
    bgBadge: 'bg-purple-500/15 text-purple-600 dark:text-purple-400 border-purple-500/30',
    category: 'SPECIAL',
    formType: 'human',
    gender: 'female',
    archetype: 'Streamer'
  },
  {
    id: 'yandere',
    name: 'Thiếu Nữ Yandere',
    title: 'Tình Yêu Cuồng Si',
    tagline: 'Tóc tím đậm, nơ đỏ: Cậu chỉ được học với một mình tớ thôi... Nhìn ai là biết tay ❤️🔪',
    emoji: '🔪',
    accent: '#9f1239',
    bgBadge: 'bg-rose-900/15 text-rose-600 dark:text-rose-400 border-rose-900/30',
    category: 'SPECIAL',
    formType: 'human',
    gender: 'female',
    archetype: 'Yandere nhẹ'
  },
  {
    id: 'gamer',
    name: 'Cao Thủ Leo Rank',
    title: 'Gamer Siêu Cấp',
    tagline: 'Tai nghe gaming, tóc xanh cyan: Coi câu hỏi như quái vật, farm sạch bài tập!',
    emoji: '🎮',
    accent: '#8b5cf6',
    bgBadge: 'bg-purple-500/15 text-purple-600 dark:text-purple-400 border-purple-500/30',
    category: 'FUN',
    formType: 'human',
    gender: 'female',
    archetype: 'Game addict'
  },
  {
    id: 'ninja',
    name: 'Nhẫn Giả Bóng Đêm',
    title: 'Shinobi Nhạy Bén',
    tagline: 'Khăn che mặt ninja, băng trán bạc: Xuất quỷ nhập thần, tốc chiến tốc thắng',
    emoji: '🥷',
    accent: '#334155',
    bgBadge: 'bg-slate-700/15 text-slate-700 dark:text-slate-300 border-slate-700/30',
    category: 'COOL',
    formType: 'human',
    gender: 'male',
    archetype: 'Ninja'
  },
  {
    id: 'mage',
    name: 'Đại Pháp Sư',
    title: 'Pháp Sư Tối Cao',
    tagline: 'Mũ phù thủy tím chóp sao vàng: Khai mở ma pháp ngôn từ, giải mã cổ ngữ',
    emoji: '🧙‍♂️',
    accent: '#6366f1',
    bgBadge: 'bg-indigo-500/15 text-indigo-600 dark:text-indigo-400 border-indigo-500/30',
    category: 'FANTASY',
    formType: 'human',
    gender: 'male',
    archetype: 'Pháp sư'
  },
  {
    id: 'princess',
    name: 'Công Chúa Tuyết Hoa',
    title: 'Công Chúa Đài Các',
    tagline: 'Vương miện vàng ngọc lục bảo, tóc vàng óng: Dịu dàng, lễ phép và thuần khiết',
    emoji: '👑',
    accent: '#f472b6',
    bgBadge: 'bg-pink-500/15 text-pink-600 dark:text-pink-400 border-pink-500/30',
    category: 'FANTASY',
    formType: 'human',
    gender: 'female',
    archetype: 'Công chúa'
  },
  {
    id: 'knight',
    name: 'Kỵ Sĩ Thánh Điện',
    title: 'Hiệp Sĩ Danh Dự',
    tagline: 'Mũ giáp kỵ sĩ bạc lông vũ xanh: Thề lấy khiên kiếm bảo vệ học trò vượt kỳ thi',
    emoji: '🛡️',
    accent: '#0284c7',
    bgBadge: 'bg-sky-500/15 text-sky-600 dark:text-sky-400 border-sky-500/30',
    category: 'FANTASY',
    formType: 'human',
    gender: 'male',
    archetype: 'Hiệp sĩ'
  },
  {
    id: 'vampire',
    name: 'Bá Tước Vampire',
    title: 'Bá Tước Bóng Đêm',
    tagline: 'Da trắng quý tộc, cổ áo Dracula nhung đỏ: Máu kẻ lười rất đắng, hãy làm bài tử tế...',
    emoji: '🧛',
    accent: '#881337',
    bgBadge: 'bg-red-900/15 text-red-600 dark:text-red-400 border-red-900/30',
    category: 'FANTASY',
    formType: 'human',
    gender: 'male',
    archetype: 'Vampire'
  },
  {
    id: 'demon_lord',
    name: 'Chúa Tể Ma Vương',
    title: 'Ma Vương Bóng Đêm',
    tagline: 'Sừng quỷ bóng đêm ấn ký đỏ: Lũ phàm nhân... Dám lười ta thiêu rụi linh hồn!',
    emoji: '😈',
    accent: '#be123c',
    bgBadge: 'bg-rose-600/15 text-rose-600 dark:text-rose-400 border-rose-600/30',
    category: 'FANTASY',
    formType: 'human',
    gender: 'male',
    archetype: 'Ma vương'
  },
  {
    id: 'chuuni',
    name: 'Wibu Phong Ấn',
    title: 'Chuunibyou Tà Nhãn',
    tagline: 'Cánh tay phải ta đang phong ấn sức mạnh hắc ám... Đừng làm ta phải kích hoạt!',
    emoji: '⚡',
    accent: '#e11d48',
    bgBadge: 'bg-rose-500/15 text-rose-600 dark:text-rose-400 border-rose-500/30',
    category: 'FUN',
    formType: 'human',
    gender: 'male',
    archetype: 'Wibu ảo'
  },

  // ================= THẦN THOẠI & HUYỀN ẢO =================
  {
    id: 'dragon',
    name: 'Long Đế Bá Vương',
    title: 'Rồng Thần Tối Cao',
    tagline: 'Sừng vàng vương miện rồng, khí chất bá đạo, miệng cay độc tâm ấm áp',
    emoji: '🐲',
    accent: '#dc2626',
    bgBadge: 'bg-red-500/15 text-red-600 dark:text-red-400 border-red-500/30',
    category: 'COOL',
    formType: 'mythical',
    gender: 'male',
    archetype: 'Cao lãnh'
  },
  {
    id: 'slime',
    name: 'Bé Slime Ma Pháp',
    title: 'Slime Tinh Linh',
    tagline: 'Thân tròn núng nính trong suốt đội vương miện mini, siêu đáng yêu',
    emoji: '💧',
    accent: '#06b6d4',
    bgBadge: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400 border-cyan-500/30',
    category: 'FANTASY',
    formType: 'mythical',
    gender: 'neutral',
    archetype: 'Slime phép thuật'
  },
  {
    id: 'ghost',
    name: 'Tiểu Hồn Ma Cute',
    title: 'Ghost Thân Thiện',
    tagline: 'Bóng ma trắng bay bổng đội mũ phù thủy nhỏ, không dọa ai chỉ nhắc học',
    emoji: '👻',
    accent: '#a855f7',
    bgBadge: 'bg-purple-500/15 text-purple-600 dark:text-purple-400 border-purple-500/30',
    category: 'FANTASY',
    formType: 'mythical',
    gender: 'neutral',
    archetype: 'Hồn ma cute'
  },
  {
    id: 'robot',
    name: 'Cyber Robot AI',
    title: 'Mecha Trí Tuệ',
    tagline: 'Khung máy kim loại, mắt LED kỹ thuật số, tối ưu hóa thuật toán ghi nhớ não bộ',
    emoji: '🤖',
    accent: '#10b981',
    bgBadge: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/30',
    category: 'SPECIAL',
    formType: 'cyber',
    gender: 'neutral',
    archetype: 'Hacker'
  },

  // ================= LINH VẬT ĐỘNG VẬT ĐỘC BẢN (KHÔNG TRÙNG LOÀI) =================
  {
    id: 'owl',
    name: 'Cú Học Giả',
    title: 'Cú Trí Tuệ Xanh',
    tagline: 'Linh vật Cú duy nhất: Mũ cử nhân, kính tròn tri thức, ghi nhớ siêu phàm',
    emoji: '🦉',
    accent: '#059669',
    bgBadge: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/30',
    category: 'POWER',
    formType: 'animal',
    gender: 'male',
    archetype: 'Hiệu trưởng'
  },
  {
    id: 'cat',
    name: 'Mèo Cam Đeo Chuông',
    title: 'Mèo Chăm Chỉ',
    tagline: 'Linh vật Mèo duy nhất: Vòng cổ đỏ chuông vàng, cần mẫn ghi chép từng bài học',
    emoji: '🐱',
    accent: '#f97316',
    bgBadge: 'bg-orange-500/15 text-orange-600 dark:text-orange-400 border-orange-500/30',
    category: 'COOL',
    formType: 'animal',
    gender: 'female',
    archetype: 'Tsundere'
  },
  {
    id: 'shiba',
    name: 'Cún Shiba Vàng',
    title: 'Shiba Năng Động',
    tagline: 'Linh vật Chó duy nhất: Khăn bandana đỏ, nụ cười tỏa nắng tràn trề sinh lực',
    emoji: '🐕',
    accent: '#d97706',
    bgBadge: 'bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/30',
    category: 'FUN',
    formType: 'animal',
    gender: 'male',
    archetype: 'Vui vẻ'
  },
  {
    id: 'fox',
    name: 'Cáo Cam Kính Tròn',
    title: 'Cáo Lanh Lợi',
    tagline: 'Linh vật Cáo duy nhất: Kính gọng vàng, phân tích nhạy bén từng cấu trúc',
    emoji: '🦊',
    accent: '#ea580c',
    bgBadge: 'bg-orange-600/15 text-orange-600 dark:text-orange-400 border-orange-600/30',
    category: 'COOL',
    formType: 'animal',
    gender: 'female',
    archetype: 'Kuudere'
  },
  {
    id: 'bear',
    name: 'Gấu Nâu Mũ Beret',
    title: 'Gấu Trầm Tĩnh',
    tagline: 'Linh vật Gấu duy nhất: Mũ beret xanh biển, kiên trì, từng bước vững chắc',
    emoji: '🐻',
    accent: '#92400e',
    bgBadge: 'bg-yellow-600/15 text-yellow-700 dark:text-yellow-400 border-yellow-600/30',
    category: 'FRIEND',
    formType: 'animal',
    gender: 'male',
    archetype: 'Bạn thân'
  },
  {
    id: 'bunny',
    name: 'Bé Thỏ Trắng',
    title: 'Thỏ Con Tốc Độ',
    tagline: 'Linh vật Thỏ duy nhất: Tai dài hồng thắt hoa vàng, phản xạ nhanh như chớp',
    emoji: '🐰',
    accent: '#f43f5e',
    bgBadge: 'bg-rose-500/15 text-rose-600 dark:text-rose-400 border-rose-500/30',
    category: 'FRIEND',
    formType: 'animal',
    gender: 'female',
    archetype: 'Em gái'
  },
  {
    id: 'penguin',
    name: 'Cánh Cụt Mùa Đông',
    title: 'Cánh Cụt Kiên Trì',
    tagline: 'Linh vật Cánh Cụt duy nhất: Nón len đỏ nơ cổ vàng, kỷ luật thép nơi băng giá',
    emoji: '🐧',
    accent: '#0f172a',
    bgBadge: 'bg-slate-800/15 text-slate-800 dark:text-slate-300 border-slate-800/30',
    category: 'POWER',
    formType: 'animal',
    gender: 'male',
    archetype: 'Hiệu trưởng'
  },
  {
    id: 'wolf',
    name: 'Sói Xám Tổng Tài',
    title: 'Sói Lãnh Tụ',
    tagline: 'Linh vật Sói duy nhất: Cà vạt xanh cyan sắc sảo, kỷ luật và quyết đoán',
    emoji: '🐺',
    accent: '#475569',
    bgBadge: 'bg-slate-600/15 text-slate-600 dark:text-slate-400 border-slate-600/30',
    category: 'POWER',
    formType: 'animal',
    gender: 'male',
    archetype: 'Chủ tịch'
  },
  {
    id: 'swan',
    name: 'Thiên Nga Vương Miện',
    title: 'Nữ Hoàng Thiên Nga',
    tagline: 'Linh vật Thiên Nga duy nhất: Vương miện tím kiêu sa, ngự trị muôn loài',
    emoji: '🦢',
    accent: '#9333ea',
    bgBadge: 'bg-purple-500/15 text-purple-600 dark:text-purple-400 border-purple-500/30',
    category: 'POWER',
    formType: 'animal',
    gender: 'female',
    archetype: 'Nữ hoàng'
  },
  {
    id: 'lion',
    name: 'Sư Tử Bờm Vàng',
    title: 'Thủ Lĩnh Sư Tử',
    tagline: 'Linh vật Sư Tử duy nhất: Kính một tròng monocle hoàng gia, bá khí áp đảo',
    emoji: '🦁',
    accent: '#b45309',
    bgBadge: 'bg-amber-600/15 text-amber-700 dark:text-amber-300 border-amber-600/30',
    category: 'POWER',
    formType: 'animal',
    gender: 'male',
    archetype: 'Thủ lĩnh'
  },
  {
    id: 'deer',
    name: 'Hươu Sừng Pha Lê',
    title: 'Hươu Rừng Thông Thái',
    tagline: 'Linh vật Hươu duy nhất: Sừng ngọc lục bảo phát sáng, phong thái danh gia vọng tộc',
    emoji: '🦌',
    accent: '#0d9488',
    bgBadge: 'bg-teal-500/15 text-teal-600 dark:text-teal-400 border-teal-500/30',
    category: 'COOL',
    formType: 'animal',
    gender: 'male',
    archetype: 'Quý tộc'
  },
  {
    id: 'panther',
    name: 'Hắc Báo Sát Thủ',
    title: 'Hắc Báo Ẩn Thân',
    tagline: 'Linh vật Báo Đen duy nhất: Khăn quàng đêm xanh thẳm, tốc độ và bí ẩn',
    emoji: '🐆',
    accent: '#1e293b',
    bgBadge: 'bg-slate-700/15 text-slate-700 dark:text-slate-300 border-slate-700/30',
    category: 'COOL',
    formType: 'animal',
    gender: 'male',
    archetype: 'CEO trẻ'
  },
  {
    id: 'villain',
    name: 'Quạ Đen Hắc Ám',
    title: 'Quạ Bóng Đêm',
    tagline: 'Linh vật Quạ duy nhất: Lông vũ tím đậm, nụ cười khẩy tà mị trên sai lầm',
    emoji: '🦅',
    accent: '#7c3aed',
    bgBadge: 'bg-violet-500/15 text-violet-600 dark:text-violet-400 border-violet-500/30',
    category: 'COOL',
    formType: 'animal',
    gender: 'male',
    archetype: 'Phản diện'
  },
  {
    id: 'memegirl',
    name: 'Ếch Xanh Meme Pepe',
    title: 'Meme Queen Ếch',
    tagline: 'Linh vật Ếch duy nhất: Mũ lưỡi trai xanh, bắn meme liên tục, tấu hài giải tỏa căng thẳng',
    emoji: '🐸',
    accent: '#22c55e',
    bgBadge: 'bg-green-500/15 text-green-600 dark:text-green-400 border-green-500/30',
    category: 'FUN',
    formType: 'animal',
    gender: 'female',
    archetype: 'Meme girl'
  },
  {
    id: 'chaotic',
    name: 'Khỉ Nâu Tinh Nghịch',
    title: 'Khỉ Siêu Quậy',
    tagline: 'Linh vật Khỉ duy nhất: Khăn bandana cam, học theo phong cách phá cách bùng nổ',
    emoji: '🐵',
    accent: '#ea580c',
    bgBadge: 'bg-orange-500/15 text-orange-600 dark:text-orange-400 border-orange-500/30',
    category: 'FUN',
    formType: 'animal',
    gender: 'male',
    archetype: 'Chaotic'
  },
  {
    id: 'classmate',
    name: 'Bé Hamster Bàn Bên',
    title: 'Hamster Nhút Nhát',
    tagline: 'Linh vật Hamster duy nhất: Kẹp cỏ 4 lá, ôm hạt hướng dương, má ửng hồng',
    emoji: '🐹',
    accent: '#10b981',
    bgBadge: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/30',
    category: 'FRIEND',
    formType: 'animal',
    gender: 'female',
    archetype: 'Bạn cùng lớp'
  },

  // Aliases for compatibility
  {
    id: 'president',
    name: 'Chủ Tịch Sói',
    title: 'Tổng Tài Cao Lãnh',
    tagline: 'Kỷ luật thép, chuẩn xác tuyệt đối',
    emoji: '🐺',
    accent: '#0284c7',
    bgBadge: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400 border-cyan-500/30',
    category: 'POWER',
    formType: 'animal',
    gender: 'male',
    archetype: 'Chủ tịch'
  },
  {
    id: 'leader',
    name: 'Thủ Lĩnh Sư Tử',
    title: 'Thủ Lĩnh Tối Cao',
    tagline: 'Khí chất áp đảo vạn người',
    emoji: '🦁',
    accent: '#b45309',
    bgBadge: 'bg-amber-600/15 text-amber-700 dark:text-amber-300 border-amber-600/30',
    category: 'POWER',
    formType: 'animal',
    gender: 'male',
    archetype: 'Thủ lĩnh'
  },
  {
    id: 'queen',
    name: 'Nữ Hoàng Thiên Nga',
    title: 'Nữ Hoàng Đế Chế',
    tagline: 'Kiêu sa quyền quý muôn loài',
    emoji: '🦢',
    accent: '#9333ea',
    bgBadge: 'bg-purple-500/15 text-purple-600 dark:text-purple-400 border-purple-500/30',
    category: 'POWER',
    formType: 'animal',
    gender: 'female',
    archetype: 'Nữ hoàng'
  },
  {
    id: 'noble',
    name: 'Hươu Quý Tộc',
    title: 'Danh Gia Vọng Tộc',
    tagline: 'Phong thái thượng lưu tinh anh',
    emoji: '🦌',
    accent: '#0d9488',
    bgBadge: 'bg-teal-500/15 text-teal-600 dark:text-teal-400 border-teal-500/30',
    category: 'COOL',
    formType: 'animal',
    gender: 'male',
    archetype: 'Quý tộc'
  },
  {
    id: 'bestie',
    name: 'Gấu Bro Chí Cốt',
    title: 'Bạn Thân Bỗ Bã',
    tagline: 'Cùng cày nát đề thi, lười là ăn đòn',
    emoji: '🐻',
    accent: '#92400e',
    bgBadge: 'bg-yellow-600/15 text-yellow-700 dark:text-yellow-400 border-yellow-600/30',
    category: 'FRIEND',
    formType: 'animal',
    gender: 'male',
    archetype: 'Bạn thân'
  },
  {
    id: 'hacker',
    name: 'Cyber Hacker',
    title: 'Hacker Mạng Ngầm',
    tagline: 'Bypass mọi giới hạn ngữ pháp',
    emoji: '🤖',
    accent: '#10b981',
    bgBadge: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/30',
    category: 'SPECIAL',
    formType: 'cyber',
    gender: 'neutral',
    archetype: 'Hacker'
  }
];
